### ISSUE TITLE
regular expression on value field

### ISSUE THREAD

**Issue by danifdezalonso** [Dhruv-Techapps/auto-clicker-auto-fill#107]
Be able to use regular expressions in the value field. For example, I need a random number value with a range (let's say from 10 to 25).

**Comment by dharmesh-hemaram** [comment]
We implemented Fix in DEV version try out `<random(1[0-9]|2[0-5])>` This will generate random number between `10-25`.

Release: https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/releases/tag/untagged-39d064e785bd029e69ec
version: 3.4.71

**Comment by danifdezalonso** [comment]
Works perfectly! Thanks!

**Comment by danifdezalonso** [comment]
It's not working anymore 🤔 
Release link is alo not working

**Comment by dharmesh-hemaram** [comment]
We redeployed changes on dev and beta 3.4.74

**Comment by dharmesh-hemaram** [comment]
This issue is fixed with versiono `3.4.74`
