### ISSUE TITLE
Beta\Dev error in Edge

### ISSUE THREAD

**Issue by KannaSakura** [Dhruv-Techapps/auto-clicker-auto-fill#115]
Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): Invalid extension id: 'DEV'

**Comment by dharmesh-hemaram** [comment]
Thank you for informing we have published extension on DEV and Beta on Edge. but we are planing to maintain only stable version on Edge

**Comment by dharmesh-hemaram** [comment]
We removed DEV and Beta version from edge. only stable version will be available
