### ISSUE TITLE
Remove Element Finder and update value not working.

### ISSUE THREAD

**Issue by mean-cj** [Dhruv-Techapps/auto-clicker-auto-fill#150]
Hi

I test on https://dev.getautoclicker.com/

# 1 Remove element does not working.
When I click on the trash icon to delete an element,  it deletes the wrong 

For example, I click to delete element 9 but it deletes element 1 instead.
Is the remove element index button sometimes incorrect?

# 2 Value not update
When i update the value of Element Finder, Action saved successfully!  ,
after browser reload the value is not update.

![image](https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/assets/1191385/2d7e8bf3-eb03-42d9-b426-409da5dfec02)

https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/assets/1191385/47cea67f-9269-4080-9b73-3c3629a8e7d8

**Comment by dharmesh-hemaram** [comment]
Thank you for letting us know this issue
