### ISSUE TITLE
Paste from clipboard 

### ISSUE THREAD

**Issue by Emoncht** [Dhruv-Techapps/auto-clicker-auto-fill#195]
I noticed that no other plugin has Paste option from clipboard/Last copied text. I think its a chrome issue that developers are unable to solve.

In my I am using a text input field. And I need to paste the last copied text into the text input field, i attached the configuration here
[Config.json](https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/files/14396230/shop.garena.my_app_100067_idlogin.json)

WHen I open the webpage I am using FormEvents::focus on the input field and then manually clicked CTRL+V in the keyboard. If there was any option to simulate the PASTE please let me know, and it will be helpful if you intigrate this feature.

**Comment by dharmesh-hemaram** [comment]
Hi @Emoncht 

If you are copying and pasting the content from same webpage itself . in this case you can use our copy paste command as ref below.

https://getautoclicker.com/docs/3.x/action-value/copy/ - it copy to localstorage
https://getautoclicker.com/docs/3.x/action-value/paste/ - it paste from localstorage.

Do let me know if this helps.

**Comment by dharmesh-hemaram** [comment]
Added Clipboard copy paste functionality into [DEV](https://dev.getautoclicker.com/).

Checkout docs on how to use same https://getautoclicker.com/docs/3.x/action-value/clipboard/

**Comment by Emoncht** [comment]
Ohh yeah, Works like a charms. I was using tampermonkey witha custom script before only for this feature. Good thing that i dont have to use any extra plugin now! Thanks a lot
