### ISSUE TITLE
Doesn't load config if the webpage doesn't refresh.

### ISSUE THREAD

**Issue by Emoncht** [Dhruv-Techapps/auto-clicker-auto-fill#204]
Hello, now a days most of the website is using next js/React js. for the automation I noticed that if the page doesn't reload(In next/react js page do not reload) then config do not fire. 

I need to reload the page manually in order to load the configuration, SO I am suggesting that config should load even if the page doesn't reload/refreshed.

**Comment by dharmesh-hemaram** [comment]
Checkout this configuration https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/discussions/72
