### ISSUE TITLE
Option to reload the URL in case if refreshing the page doesn't come back refreshed

### ISSUE THREAD

**Issue by kazuna** [Dhruv-Techapps/auto-clicker-auto-fill#40]
Discussed on the discord page:
https://discord.com/channels/702091948902711388/1183887068833783828

Me:
I think something else needs to reopen the page after issuing a refresh or reload but only when the page ends up with the error page. That's why I came up with the original idea that the extension refreshes the page and waits for the page to refresh (the wait time is customizable), if the page doesn't come back refreshed, then the extension reopens the page because the page is likely showing the error page or the ad page.

You:
Hmmmm I will do check on this . We need to develop this feature by tracking the current page status and reopen from background page.

**Comment by dharmesh-hemaram** [comment]
We have added additional functionality to refresh page from background script . Please update to latest version ( >= v3.4.77)  of DEV / BETA. and use `LocationCommand::reload::background` to reload from background
