### ISSUE TITLE
value feed is not supporting gogle sheet input in addon 

### ISSUE THREAD

**Issue by betagoyal** [Dhruv-Techapps/auto-clicker-auto-fill#65]
please integrate google sheet input in value of addon .
need to change value every hour 
![Capture1](https://github.com/Dhruv-Techapps/auto-click-auto-fill/assets/16471212/7d2c50e3-120a-4e82-9802-2d68d45f99a8)
![Capture2](https://github.com/Dhruv-Techapps/auto-click-auto-fill/assets/16471212/c50d18ea-3d95-4c20-a218-225ff80eb1ef)

**Comment by dharmesh-hemaram** [comment]
Changes available on DEV | BETA
