### ISSUE TITLE
Configuration bug

### ISSUE THREAD

**Issue by bzkyyusn** [Dhruv-Techapps/auto-clicker-auto-fill#68]
Describe the bug
The configuration only runs after I reload (F5) the page.

To Reproduce
1. Go to '[https://www.urbtix.hk/payment-information/]'
2. The configuration does not run, but shows "Done" at the extension tool bar
3. Reload (F5) the page
4. The configuration works

Expected behavior
The configuration shall work after the page was first loaded.

Desktop
 - OS: Windows 11
 - Browser: chrome
 - Version: 118.0.5993.118

**Comment by dharmesh-hemaram** [comment]
@Luckymaxyk  https://github.com/Dhruv-Techapps/auto-clicker-auto-fill/issues/68#issuecomment-1874167439

> We added new feature to add random string `<random(sun|mon|tue|wednes|thurs|fri|satur)day>` this will generate random string based on day

Release : DEV 
Version : 3.4.71

**Comment by dharmesh-hemaram** [comment]
@bzkyyusn - Can you provide configuration and communicate on Discord server for queries.

**Comment by dharmesh-hemaram** [comment]
Closing this ticket as no answer
